### ISSUE TITLE
Film an explainer video?

### ISSUE THREAD

**Issue by colinloretz** [hack4reno/hack4reno2015#7]
A lot of people have said its not immediately clear what the Summit is. We could do a quick video to introduce the event and promote it on social.

**Comment by colinloretz** [comment]
@neazle do you have some time this weekend? We can bust this out

**Comment by neazle** [comment]
Yup.

On Thu, Oct 15, 2015 at 11:30 AM, Colin Loretz notifications@github.com
wrote:

> @neazle https://github.com/neazle do you have some time this weekend?
> We can bust this out
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hack4reno/hack4reno2015/issues/7#issuecomment-148481699
> .

## 

_Monica Thompson_
(775) 843-9889
monica@monicacthompson.com
@monicaxthompson https://twitter.com/blam84
